language: php

php:
  - 7.1

services:
  - docker

before_install:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e $SSH_KEY > ~/.ssh/id_rsa.pub
  - chmod 600 ~/.ssh/id_rsa*
  - eval `ssh-agent -s`

  # Install Lando
  - sudo apt-get -y update
  - sudo apt-get -y install cgroup-bin curl
  - curl -fsSL -o /tmp/lando.deb https://github.com/lando/lando/releases/download/v3.0.0-beta.39/lando-v3.0.0-beta.39.deb
  - sudo dpkg -i /tmp/lando.deb

  # Sanity check to make sure we are rolling
  - lando version

script:

  # Switch the travis build files and start
  - rm -rf .gitignore
  - cp -rf .travis/.lando.gitignore .gitignore
  - rm -f .lando.yml
  - cp -rf .travis/.lando.travis.yml .lando.yml
  - lando start -- -v

after_success:

  # Setup git to push to DO.
  - git config --global user.email labboy0276@yahoo.com
  - git config --global user.name "John Ouellet"
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - git remote add drupalorg labboy0276@git.drupal.org:project/minimis.git

  - git add -A
  - git commit -m ${MESSAGE}
  - git push drupalorg master