# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201711-01

    working_directory: ~/minimis

    steps:
      - checkout

      - run:
          name: Setup Lando
          command: |
            sudo apt-get -y update
            sudo apt-get -y install cgroup-bin curl
            curl -fsSL -o /tmp/lando.deb https://github.com/lando/lando/releases/download/v3.0.0-beta.39/lando-v3.0.0-beta.39.deb
            sudo dpkg -i /tmp/lando.deb
            lando version

      - run:
          name: Prep For Pushing
          command: |
            rm -rf .gitignore
            cp -rf .circleci/.lando.gitignore .gitignore
            rm -f .lando.yml
            cp -rf .circleci/.lando.travis.yml .lando.yml
            lando start -- -v
            ls -l