errorClass: b-error
loadInvisible: false
offset: 100
saveViewportOffsetDelay: '50'
selector: b-lazy
alter_tag:
  img: img
  iframe: iframe
skipClass: no-b-lazy
src: data-src
successClass: b-loaded
validateDelay: '25'
placeholderSrc: 'data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=='
image_fields: true
_core:
  default_config_hash: 4fKLAfCqFJg0OWqH1mAuoOLR9YCxmOnu_RYfF-yMhzA
